db.url=jdbc:mysql://localhost:3306/biblioteca_marc21?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=

# Configurações do servidor de e-mail (Mailtrap/SMTP para testes)
smtp.host=sandbox.smtp.mailtrap.io
smtp.port=2525
smtp.user=b0d8c2f374139b
smtp.password=56e1390f093055
